app_name = "awesome web"

# possible values: DEBUG, INFO, WARNING, ERROR, FATAL
log_level = "DEBUG"
#自行配置
[mysql]
user = "root"
password = "123456"
host = "mysql"
port = "3306"
db = "bottle"

[redis]
host = "redis"
port = "6379"

